---

- name: Git checkout tfenv
  git:
    repo: 'https://github.com/tfutils/tfenv'
    dest: /usr/local/lib/tfenv
    version: master
  register: result

- name: Install tfenv binary
  file:
    src: /usr/local/lib/tfenv/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  loop:
    # - terraform
    - tfenv
  when: result is success and not ansible_check_mode
  register: result

- name: Install and setup terraform
  shell: 
    cmd: |
      tfenv install '{{ tf_version }}'
      tfenv use '{{ tf_version }}'
    chdir: ~
    creates: "/usr/local/lib/tfenv/versions/'{{ tf_version }}'/terraform"
  when: not ansible_check_mode

# Autocomplete for bash and zsh
# grep -q ".local/lib/tfenv/versions/'{{ tf_version }}'/terraform" ~/.bashrc ~/.zshrc && true || terraform -install-autocomplete
