---

- name: Git checkout tfenv
  git:
    repo: 'https://github.com/tfutils/tfenv'
    dest: $HOME/.tfenv
    version: master
  register: result

- name: Create local binary path
  file:
    path: $HOME/.local/bin
    state: directory
    
- name: Install tfenv binary
  file:
    src: $HOME/.tfenv/bin/{{ item }}
    dest: $HOME/.local/bin/{{ item }}
    state: link
  loop:
    - tfenv
    - terraform
  when: result is success and not ansible_check_mode
  register: result

- name: Install and setup terraform
  shell: |
      . $HOME/.profile
      tfenv install {{ item }}
  loop: '{{ tf_versions }}'
  when: not ansible_check_mode

# Autocomplete for bash and zsh
# grep -q ".local/lib/tfenv/versions/'{{ tf_version }}'/terraform" ~/.bashrc ~/.zshrc && true || terraform -install-autocomplete
